volumes:
  pg-data: {}
  keycloak_data: {}
  traefik-certificates: {}

services:
  pgsql:
    image: postgres:17
    env_file:
      - .env/pg.env
    ports:
      - "15832:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  proxy:
    image: traefik:v3.0
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"
    ports:
      - "9480:80"
      - "9444:443"
    depends_on:
      - pgsql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  casbin-api:
    image: casbinminimalapi
    build:
      context: .
      dockerfile: CasbinMinimalApi/Dockerfile
    env_file:
      - .env/api.env
      - .env/secret.env
    depends_on:
      - pgsql
      - proxy
    labels:
      - "traefik.enable=true"
      # Router HTTP
      - "traefik.http.routers.casbin-http.rule=Host(`api.casbin`)"
      - "traefik.http.routers.casbin-http.entrypoints=web"
      - "traefik.http.services.casbin.loadbalancer.server.port=8080"
      # Router HTTPS
      - "traefik.http.routers.casbin-https.rule=Host(`api.casbin`)"
      - "traefik.http.routers.casbin-https.entrypoints=websecure"
      - "traefik.http.routers.casbin-https.tls=true"
      - "traefik.http.services.casbin.loadbalancer.server.port=8080"
