// <auto-generated />
using CasbinMinimalApi.Infrastructure.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasbinMinimalApi.Persistence.Authorization.Migrations
{
    [DbContext(typeof(AuthorizationDbContext))]
    partial class AuthorizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("casbin")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Casbin.Persist.Adapter.EFCore.Entities.EFCorePersistPolicy<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("ptype");

                    b.Property<string>("Value1")
                        .HasColumnType("text")
                        .HasColumnName("v0");

                    b.Property<string>("Value2")
                        .HasColumnType("text")
                        .HasColumnName("v1");

                    b.Property<string>("Value3")
                        .HasColumnType("text")
                        .HasColumnName("v2");

                    b.Property<string>("Value4")
                        .HasColumnType("text")
                        .HasColumnName("v3");

                    b.Property<string>("Value5")
                        .HasColumnType("text")
                        .HasColumnName("v4");

                    b.Property<string>("Value6")
                        .HasColumnType("text")
                        .HasColumnName("v5");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Value1");

                    b.HasIndex("Value2");

                    b.HasIndex("Value3");

                    b.HasIndex("Value4");

                    b.HasIndex("Value5");

                    b.HasIndex("Value6");

                    b.ToTable("casbin_rule", "casbin");
                });
#pragma warning restore 612, 618
        }
    }
}
